import { SvgIconComponent } from '@mui/icons-material';
import {
  AccountBalance,
  AccountBalanceWallet,
  AccountBox,
  AccountCircle,
  AccountTree,
  Analytics,
  AreaChart,
  AssuredWorkload,
  Atm,
  AttachMoney,
  Backup,
  Business,
  BusinessCenter,
  CandlestickChart,
  CorporateFare,
  CreditCard,
  CreditScore,
  CurrencyBitcoin,
  CurrencyExchange,
  CurrencyFranc,
  CurrencyLira,
  CurrencyPound,
  CurrencyRuble,
  CurrencyRupee,
  CurrencyYen,
  CurrencyYuan,
  DataSaverOn,
  DataThresholding,
  Domain,
  EmojiEvents,
  FlagCircle,
  Insights,
  Key,
  Lock,
  ManageAccounts,
  MonetizationOn,
  MultilineChart,
  Paid,
  Payment,
  Payments,
  PieChartOutline,
  PivotTableChart,
  PriceCheck,
  QrCode2,
  QueryStats,
  ReceiptLong,
  Savings,
  Security,
  Settings,
  ShowChart,
  StackedLineChart,
  StarOutline,
  SupervisorAccount,
  SwapHoriz,
  SyncAlt,
  Timeline,
  TrackChanges,
  TrendingDown,
  TrendingUp,
  VerifiedUser,
  Wallet,
  WorkspacePremium,
} from '@mui/icons-material';

export const bankAccountIconMap: Record<string, SvgIconComponent> = {
  // 🏦 Banks & Institutions
  AccountBalance,
  Business,
  CorporateFare,
  AccountBalanceWallet,
  Payments,
  Domain,
  BusinessCenter,
  AssuredWorkload,
  // 💳 Cards & Transactions
  CreditCard,
  Payment,
  Atm,
  CreditScore,
  ReceiptLong,
  SwapHoriz,
  SyncAlt,
  QrCode2,
  PriceCheck,
  // 📊 Analytics & Insights
  Analytics,
  Insights,
  QueryStats,
  ShowChart,
  Timeline,
  StackedLineChart,
  MultilineChart,
  CandlestickChart,
  AreaChart,
  PieChartOutline,
  PivotTableChart,
  DataThresholding,
  // 💰 Savings, Investments & Growth
  Savings,
  MonetizationOn,
  AttachMoney,
  Paid,
  TrendingUp,
  TrendingDown,
  AccountTree,
  CurrencyExchange,
  // 🪙 Currencies
  CurrencyBitcoin,
  CurrencyPound,
  CurrencyYen,
  CurrencyRupee,
  CurrencyFranc,
  CurrencyYuan,
  CurrencyLira,
  CurrencyRuble,
  // 🏠 Personal, Goals & Achievements
  Wallet,
  EmojiEvents,
  FlagCircle,
  WorkspacePremium,
  StarOutline,
  VerifiedUser,
  TrackChanges,
  // ⚙️ Utility & Account Management
  ManageAccounts,
  SupervisorAccount,
  AccountCircle,
  Key,
  Lock,
  Security,
  Settings,
  Backup,
  DataSaverOn,
  AccountBox,
};

// Derived from the map — no need to maintain a separate string array
export const bankAccountIcons = Object.keys(bankAccountIconMap);
