export const categoryIcons = [
  // 💰 Money & Banking
  'AccountBalance',
  'AccountBalanceWallet',
  'AttachMoney',
  'CreditCard',
  'Payments',
  'MonetizationOn',
  'Savings',
  'Wallet',
  'CurrencyExchange',
  'PriceChange',
  'PriceCheck',
  'TrendingUp',
  'TrendingDown',
  'ShoppingCart',
  'Receipt',
  'PointOfSale',
  'Paid',
  'Calculate',
  'RequestQuote',

  // 🛒 Shopping & Expenses
  'LocalGroceryStore',
  'Fastfood',
  'LocalDining',
  'Liquor',
  'ShoppingBag',
  'LocalMall',
  'LocalCafe',
  'LocalBar',
  'Restaurant',
  'TakeoutDining',
  'BakeryDining',
  'Store',
  'Storefront',
  'DinnerDining',
  'Icecream',
  'CardGiftcard',

  // 🏠 Housing & Utilities
  'Home',
  'Apartment',
  'Weekend',
  'Lightbulb',
  'Bolt',
  'WaterDrop',
  'GasMeter',
  'Chair',
  'Bed',
  'Shower',

  // 🚗 Transport & Travel
  'DirectionsCar',
  'Commute',
  'LocalTaxi',
  'Train',
  'Flight',
  'DirectionsBus',
  'PedalBike',
  'ElectricCar',
  'TwoWheeler',
  'AirportShuttle',
  'LocalShipping',

  // 🏥 Health & Insurance
  'LocalHospital',
  'HealthAndSafety',
  'MedicalServices',
  'Vaccines',
  'Psychology',
  'Medication',
  'MonitorHeart',
  'Bloodtype',
  'LocalPharmacy',
  'Biotech',

  // 🎉 Leisure & Lifestyle
  'SportsSoccer',
  'FitnessCenter',
  'SportsBasketball',
  'SportsEsports',
  'MusicNote',
  'Theaters',
  'LocalMovies',
  'Casino',
  'Celebration',
  'Spa',

  // 📚 Education & Work
  'School',
  'MenuBook',
  'LibraryBooks',
  'Work',
  'BusinessCenter',
  'LaptopMac',
  'DesktopWindows',
  'CastForEducation',
  'WorkspacePremium',
  'Subscriptions',

  // 🛠️ General / Other
  'Category',
  'Label',
  'Folder',
  'CheckCircle',
  'Cancel',
  'Alarm',
  'CalendarMonth',
  'Event',
  'ShoppingBasket',
  'LocalAtm',
  'Settings',
  'Build',
  'Info',
];
